Dataset splits:
Training samples: 896
Validation samples: 100
Test samples: 249
Traceback (most recent call last):
  File "/Users/nataliedellamaria/dev/shutter-speed/film-processing/model.py", line 209, in <module>
    model, history = train_and_evaluate_model(
  File "/Users/nataliedellamaria/dev/shutter-speed/film-processing/model.py", line 158, in train_and_evaluate_model
    WandbModelCheckpoint("models")]
  File "/Users/nataliedellamaria/Library/Python/3.9/lib/python/site-packages/wandb/integration/keras/callbacks/model_checkpoint.py", line 90, in __init__
    super().__init__(
  File "/Users/nataliedellamaria/Library/Python/3.9/lib/python/site-packages/keras/src/callbacks/model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=models
Traceback (most recent call last):
  File "/Users/nataliedellamaria/dev/shutter-speed/film-processing/model.py", line 209, in <module>
    model, history = train_and_evaluate_model(
  File "/Users/nataliedellamaria/dev/shutter-speed/film-processing/model.py", line 158, in train_and_evaluate_model
    WandbModelCheckpoint("models")]
  File "/Users/nataliedellamaria/Library/Python/3.9/lib/python/site-packages/wandb/integration/keras/callbacks/model_checkpoint.py", line 90, in __init__
    super().__init__(
  File "/Users/nataliedellamaria/Library/Python/3.9/lib/python/site-packages/keras/src/callbacks/model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=models
